### ISSUE TITLE
How to install static globally

### ISSUE THREAD

**Issue by Kikobeats** [apex/static#19]
Hey,

I'm a frequent npm user, so `npm install -g` is very familiar to me, but no idea how to install it globally.

I suppose the tricky way is make a `go get` and then link the path inside `$PATH`, but ugh, seriously?

But problem if this is the right way, but again no idea. 

Thanks for this fantastic project!

**Comment by tj** [comment]
Yea all you need is `go get github.com/apex/static/...` to grab the commands, or more specifically `go get github.com/apex/static/cmd/static-docs`. No need to link anything if you have $GOPATH/bin in your $PATH
