### ISSUE TITLE
have a way to edit the theme views without the command overriding changes

### ISSUE THREAD

**Issue by caarlos0** [apex/static#22]
as discussed in https://github.com/apex/static/pull/12#issuecomment-328397008

@tj I can help with that, but I'm not sure how's the best way of doing it.

I was thinking about maybe having a custom `head.html` that is inlined into the theme (and also maybe other "hook" files)...

what do you think?

**Comment by tj** [comment]
Hmmmm maybe by default the content and theme is overridden, and we have some sub-command to save the ./theme for editing, after which it's ignored unless you explicitly update it again with that command?

**Comment by caarlos0** [comment]
@tj maybe, seems like it would be hard to update the theme later... 

for example, a fix is pushed to the theme, how do I update it without loosing my changes? (I mean, in an easy way)

**Comment by tj** [comment]
yea you'd have to merge or something, but I don't think just a head.html for example would be sufficient depending on what you want to tweak. Generally I don't think it's awful to merge if you want to apply changes, the style updates might break yours etc so there's no real seamless way to update without manually merging

**Comment by caarlos0** [comment]
yeah, that makes sense...

I guess it'll also be simpler to do that :D
